version: '2'

services:
  web:
    image: dgageot/web
    ports:
     - "80:80"
    links:
     - words:words

  words:
    image: dgageot/words
    ports:
     - "8080:8080"
    links:
     - db:mongo

  db-ui:
    image: mongo-express:0.30.43
    environment:
     - ME_CONFIG_BASICAUTH_USER="labdocker"
     - ME_CONFIG_BASICAUTH_PASSWORD="foobar"
    ports:
     - "8081:8081"
    links:
     - db:mongo

  db:
    image: mongo:3.2.4
    ports:
    - "27017:27017"
