version: '2'

services:
  web:
    build: web
    image: dockerdemos/lab-web
    ports: ["80:80"]
    links: ["words-java:words"]
    volumes: ["./web/static:/usr/share/nginx/html"]

  words-java:
    build: words-java
    image: dockerdemos/lab-words-java
    expose: ["8080"]
    links: ["db:mongo"]

  db:
    image: mongo:3.2.4
    expose: ["27017"]
