version: '2'

services:
  web:
    build: web
    ports:
     - "80:80"
    links:
     - words:words

  words:
    build: words
    ports:
     - "8080:8080"
    links:
     - db:mongo

  db-ui:
    image: mongo-express:0.30.43
    ports:
     - "8081:8081"
    links:
     - db:mongo

  db:
    image: mongo:3.2.4
    ports:
    - "27017:27017"
