version: '2'

services:
  web:
    build: web
    image: dockerdemos/lab-web
    volumes: ["./web/static:/usr/share/nginx/html"]
    ports: ["80:80"]
    depends_on: ["words"]
    networks: ["lab"]

  words:
    build: words-dispatcher
    image: dockerdemos/lab-words-dispatcher
    depends_on: ["words-java"]
    networks: ["lab"]

  words-java:
    build: words-java
    image: dockerdemos/lab-words-java
    depends_on: ["mongo"]
    # ports: ["5005:5005"]
    # command: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    networks: ["lab"]

  mongo:
    image: mongo:3.2.4
    networks: ["lab"]

networks:
  lab:
